
services:
  nuxt:
    build: .
    container_name: portafolio-luna
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development